const database = "bd3_atv2";

const collection = "bd3_atv2_produtos";

use(database);

db[collection].insertMany([
  {
    _id: 1,
    nome: "Cafeteira Elétrica",
    valor: 199.9,
    quantidadeEmEstoque: 30,
    fabricante: "Café Brasil",
    categoria: "Eletrodomésticos",
    descricao: "Cafeteira elétrica com capacidade para 12 xícaras.",
  },
  {
    _id: 2,
    nome: "Liquidificador",
    valor: 129.9,
    quantidadeEmEstoque: 25,
    fabricante: "MixMaster",
    categoria: "Eletrodomésticos",
    descricao: "Liquidificador potente com 5 velocidades e jarra de vidro.",
  },
  {
    _id: 3,
    nome: "Ferro de Passar",
    valor: 89.9,
    quantidadeEmEstoque: 15,
    fabricante: "PassaFácil",
    categoria: "Eletrodomésticos",
    descricao: "Ferro de passar a vapor com base antiaderente.",
  },
  {
    _id: 4,
    nome: "Aspirador de Pó",
    valor: 299.9,
    quantidadeEmEstoque: 20,
    fabricante: "LimpaTudo",
    categoria: "Eletrodomésticos",
    descricao: "Aspirador de pó potente com filtro HEPA.",
  },
  {
    _id: 5,
    nome: "Smartphone XYZ",
    valor: 1499.9,
    quantidadeEmEstoque: 50,
    fabricante: "TechWorld",
    categoria: "Eletrônicos",
    descricao: "Smartphone com tela de 6.5 polegadas e câmera tripla.",
  },
  {
    _id: 6,
    nome: "Notebook ABC",
    valor: 3499.9,
    quantidadeEmEstoque: 10,
    fabricante: "CompTech",
    categoria: "Eletrônicos",
    descricao: "Notebook com processador Intel i7 e 16GB de RAM.",
  },
  {
    _id: 7,
    nome: 'Smart TV 50"',
    valor: 2499.9,
    quantidadeEmEstoque: 15,
    fabricante: "VisionScreen",
    categoria: "Eletrônicos",
    descricao: "Smart TV 4K com acesso a diversos aplicativos.",
  },
  {
    _id: 8,
    nome: "Caixa de Som Bluetooth",
    valor: 199.9,
    quantidadeEmEstoque: 40,
    fabricante: "SoundWave",
    categoria: "Eletrônicos",
    descricao: "Caixa de som portátil com 12 horas de bateria.",
  },
  {
    _id: 9,
    nome: "Relógio Inteligente",
    valor: 599.9,
    quantidadeEmEstoque: 35,
    fabricante: "SmartTime",
    categoria: "Eletrônicos",
    descricao: "Relógio inteligente com monitoramento de saúde e atividades.",
  },
  {
    _id: 10,
    nome: "Bicicleta MTB",
    valor: 899.9,
    quantidadeEmEstoque: 12,
    fabricante: "BikeMania",
    categoria: "Esportes",
    descricao: "Bicicleta mountain bike com suspensão dianteira.",
  },
  {
    _id: 11,
    nome: "Tênis de Corrida",
    valor: 399.9,
    quantidadeEmEstoque: 50,
    fabricante: "RunFast",
    categoria: "Esportes",
    descricao: "Tênis de corrida com amortecimento avançado.",
  },
  {
    _id: 12,
    nome: "Camiseta Esportiva",
    valor: 89.9,
    quantidadeEmEstoque: 100,
    fabricante: "FitWear",
    categoria: "Esportes",
    descricao: "Camiseta respirável ideal para atividades físicas.",
  },
  {
    _id: 13,
    nome: "Equipamento de Musculação",
    valor: 1499.9,
    quantidadeEmEstoque: 5,
    fabricante: "FitGear",
    categoria: "Esportes",
    descricao: "Equipamento para musculação com diversas funções.",
  },
  {
    _id: 14,
    nome: "Cadeira Gamer",
    valor: 899.9,
    quantidadeEmEstoque: 20,
    fabricante: "GameSeat",
    categoria: "Games",
    descricao: "Cadeira gamer ajustável com suporte lombar.",
  },
  {
    _id: 15,
    nome: "Console de Videogame",
    valor: 2499.9,
    quantidadeEmEstoque: 10,
    fabricante: "PlayBox",
    categoria: "Games",
    descricao: "Console com jogos pré-instalados e 1TB de armazenamento.",
  },
  {
    _id: 16,
    nome: "Controle Sem Fio",
    valor: 199.9,
    quantidadeEmEstoque: 30,
    fabricante: "GamePad",
    categoria: "Games",
    descricao: "Controle sem fio compatível com diversos consoles.",
  },
  {
    _id: 17,
    nome: "Mouse Gamer",
    valor: 129.9,
    quantidadeEmEstoque: 50,
    fabricante: "GamerPro",
    categoria: "Games",
    descricao: "Mouse gamer com iluminação RGB e alta precisão.",
  },
  {
    _id: 18,
    nome: "Teclado Mecânico",
    valor: 299.9,
    quantidadeEmEstoque: 25,
    fabricante: "TypeMaster",
    categoria: "Games",
    descricao: "Teclado mecânico com switches personalizados e iluminação.",
  },
  {
    _id: 19,
    nome: "Capa de Chuva",
    valor: 49.9,
    quantidadeEmEstoque: 60,
    fabricante: "RainShield",
    categoria: "Moda",
    descricao: "Capa de chuva leve e impermeável.",
  },
  {
    _id: 20,
    nome: "Óculos de Sol",
    valor: 159.9,
    quantidadeEmEstoque: 40,
    fabricante: "SunnyLook",
    categoria: "Moda",
    descricao: "Óculos de sol com proteção UV400.",
  },
]);
