const database = "bd3_atv2";

const collection = "bd3_atv2_produtos";

use(database);

db[collection].insertMany([
  {
    _id: 21,
    nome: "Relógio Casual",
    valor: 299.9,
    quantidadeEmEstoque: 20,
    fabricante: "TimeStyle",
    categoria: "Moda",
    descricao: "Relógio casual com design moderno.",
  },
  {
    _id: 22,
    nome: "Bolsa de Couro",
    valor: 399.9,
    quantidadeEmEstoque: 15,
    fabricante: "LeatherCraft",
    categoria: "Moda",
    descricao: "Bolsa de couro legítimo com várias divisórias.",
  },
  {
    _id: 23,
    nome: "Perfume Floral",
    valor: 249.9,
    quantidadeEmEstoque: 50,
    fabricante: "Essência",
    categoria: "Beleza",
    descricao: "Perfume floral com notas de rosa e jasmim.",
  },
  {
    _id: 24,
    nome: "Creme Hidratante",
    valor: 59.9,
    quantidadeEmEstoque: 100,
    fabricante: "SkinCare",
    categoria: "Beleza",
    descricao: "Creme hidratante com propriedades nutritivas.",
  },
  {
    _id: 25,
    nome: "Sombra para Olhos",
    valor: 39.9,
    quantidadeEmEstoque: 75,
    fabricante: "MakeupPro",
    categoria: "Beleza",
    descricao: "Sombra para olhos em várias cores.",
  },
  {
    _id: 26,
    nome: "Máscara de Cílios",
    valor: 79.9,
    quantidadeEmEstoque: 50,
    fabricante: "LashBoost",
    categoria: "Beleza",
    descricao: "Máscara de cílios que alonga e volumiza.",
  },
  {
    _id: 27,
    nome: "Escova de Cabelo",
    valor: 19.9,
    quantidadeEmEstoque: 80,
    fabricante: "HairCare",
    categoria: "Beleza",
    descricao: "Escova de cabelo com cerdas macias.",
  },
  {
    _id: 28,
    nome: "Camiseta de Algodão",
    valor: 39.9,
    quantidadeEmEstoque: 150,
    fabricante: "BasicWear",
    categoria: "Moda",
    descricao: "Camiseta básica de algodão, confortável e leve.",
  },
  {
    _id: 29,
    nome: "Calça Jeans",
    valor: 149.9,
    quantidadeEmEstoque: 40,
    fabricante: "DenimStyle",
    categoria: "Moda",
    descricao: "Calça jeans com corte moderno e confortável.",
  },
  {
    _id: 30,
    nome: "Tênis Casual",
    valor: 249.9,
    quantidadeEmEstoque: 35,
    fabricante: "ComfortStep",
    categoria: "Moda",
    descricao: "Tênis casual com design elegante e conforto.",
  },

  {
    _id: 31,
    nome: "Sofá Retrátil",
    valor: 1999.9,
    quantidadeEmEstoque: 10,
    fabricante: "Conforto Móveis",
    categoria: "Móveis",
    descricao: "Sofá retrátil com estofamento macio e tecido resistente.",
  },
  {
    _id: 32,
    nome: "Mesa de Jantar",
    valor: 1299.9,
    quantidadeEmEstoque: 5,
    fabricante: "Móveis Estilo",
    categoria: "Móveis",
    descricao: "Mesa de jantar para 6 pessoas em madeira maciça.",
  },
  {
    _id: 33,
    nome: "Cadeira de Escritório",
    valor: 599.9,
    quantidadeEmEstoque: 15,
    fabricante: "ErgoChair",
    categoria: "Móveis",
    descricao: "Cadeira de escritório ergonômica com ajuste de altura.",
  },
  {
    _id: 34,
    nome: "Cama Box",
    valor: 1599.9,
    quantidadeEmEstoque: 8,
    fabricante: "Sonho Bom",
    categoria: "Móveis",
    descricao: "Cama box com colchão ortopédico para melhor descanso.",
  },
  {
    _id: 35,
    nome: "Estante de Livros",
    valor: 399.9,
    quantidadeEmEstoque: 20,
    fabricante: "Móveis Criativos",
    categoria: "Móveis",
    descricao: "Estante de livros em madeira com várias prateleiras.",
  },
  {
    _id: 36,
    nome: "Cafeteira Francesa",
    valor: 49.9,
    quantidadeEmEstoque: 50,
    fabricante: "Café Gourmet",
    categoria: "Eletrodomésticos",
    descricao: "Cafeteira francesa de vidro com capacidade para 8 xícaras.",
  },
  {
    _id: 37,
    nome: "Panela de Pressão",
    valor: 129.9,
    quantidadeEmEstoque: 30,
    fabricante: "Cozinha Rápida",
    categoria: "Eletrodomésticos",
    descricao: "Panela de pressão de alumínio com capacidade para 4L.",
  },
  {
    _id: 38,
    nome: "Escorredor de Louça",
    valor: 29.9,
    quantidadeEmEstoque: 100,
    fabricante: "Utensílios Práticos",
    categoria: "Eletrodomésticos",
    descricao: "Escorredor de louça em plástico resistente.",
  },
  {
    _id: 39,
    nome: "Lâmpada LED",
    valor: 19.9,
    quantidadeEmEstoque: 200,
    fabricante: "IluminaTech",
    categoria: "Iluminação",
    descricao: "Lâmpada LED com baixo consumo energético.",
  },
  {
    _id: 40,
    nome: "Abajur Moderno",
    valor: 89.9,
    quantidadeEmEstoque: 25,
    fabricante: "Luz Elegante",
    categoria: "Iluminação",
    descricao: "Abajur moderno com design minimalista.",
  },
  {
    _id: 41,
    nome: "Fone de Ouvido Sem Fio",
    valor: 199.9,
    quantidadeEmEstoque: 40,
    fabricante: "AudioWave",
    categoria: "Eletrônicos",
    descricao: "Fone de ouvido sem fio com cancelamento de ruído.",
  },
]);
